### ISSUE TITLE
Animáció kész

### ISSUE THREAD

**Issue by bodab** [Teaching-projects/SZE-FONYA-2021-Beadando-Substring-DFA#2]
Felraktam az új programot, ezzel létrejön az animáció az elfogadandó szóról egy gif-ben.
Lényegében itt már teljesen másképp csinálom az egész DFA-t, mint az előzőnél.
Remélem ez fedi a megbeszélt feladatot.

**Comment by hegyhati** [comment]
No, most sikerult ralesnem. 

Tyuu, ezek aztan jo sok mindent felpakoltak :-D De jopofa a gif, meg a dot-os svg is. 

Teljesen rendben vagyunk, de ami a kodszervezest illeti, ha megfogadsz egy tanacsot: nezegess videokat arrol, milyen egy szep, es konnyen ertheto kod, vagy amikor refaktoraljak valaki meglevo kodjat, hogy ilyenne valjon. Persze nem tudom, mennyire fejleszto vonalon akarsz mozogni, de ha igen, szerintem erdemes erre idot szanni. 

Legjobbakat!
